packages:
  - "sdk"
  - "docs"
  - "experiments/billable"
  - "experiments/yt-dos"
  - "experiments/cutable"
  - "experiments/zoomshare"
  - "experiments/realtime-poc"
  - "experiments/ai-stream"
  - "experiments/server-push-poc"
  - "starters/drizzle"
  - "starters/minimal"
  - "starters/passkey-auth"
  - "starters/prisma"
  - "starters/sessions"
  - "starters/standard"
